# Netlify deployment configuration
[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

# Environment variables will need to be set in Netlify dashboard
# VITE_API_URL = "https://your-backend-url.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
